### ISSUE TITLE
本地访问目标小马一直报错，菜刀就没问题，请大神指点，感激

### ISSUE THREAD

**Issue by Baibing0118** [AntSwordProject/AntSword-Loader#10]
目标地址是虚拟机的地址<img width="1048" alt="屏幕快照 2019-04-29 下午4 56 11" src="https://user-images.githubusercontent.com/32734962/56885735-c0e3a700-6a9f-11e9-90b6-5d254a5521ac.png">

**Comment by Medicean** [comment]
提供一下 shell 的配置还有服务端代码

**Comment by Baibing0118** [comment]
就是普通的一句话，密码也没问题，严格按照ant教程配置的，char类型




在2019年04月29日 17:35，Medicean 写道：

提供一下 shell 的配置还有服务端代码

**Comment by Medicean** [comment]
PHP 版本呢，大概能猜到你的虚拟机可能是 PHP4 版本的，选用 PHP4 类型，编码器配置成 base64、chr 这些

**Comment by Baibing0118** [comment]
已经在学蚁致用公众号里回复您啦、感恩


在2019年04月29日 17:45，Medicean 写道：

PHP 版本呢
