### ISSUE TITLE
ubuntu运行antsword异常

### ISSUE THREAD

**Issue by 9tail123** [AntSwordProject/AntSword-Loader#11]
ubuntu下点击antsword打不开，提示如下
could not display "AntSword"
there is no application installed for "shared library" files
请问可能是什么原因呢

**Comment by Medicean** [comment]
参考这个问题解决
https://github.com/AntSwordProject/AntSword-Loader/issues/3#issuecomment-420498191

**Comment by 9tail123** [comment]
这两个库都装上了，点击还是一样问题

**Comment by Medicean** [comment]
查了一下资料，应该是 ubuntu 的 bug 

https://bugs.launchpad.net/ubuntu/+source/file/+bug/1747711

**Comment by 9tail123** [comment]
额，好的
