### ISSUE TITLE
Windows 10下点击任务栏图标无法打开

### ISSUE THREAD

**Issue by p1ne4pple** [AntSwordProject/AntSword-Loader#14]
Windows 10下最小化后单击或双击图标打开会马上再次隐藏,右键点击显示能正常使用

**Comment by p1ne4pple** [comment]
OS 名称:          Microsoft Windows 10 家庭中文版
OS 版本:          10.0.17134 暂缺 Build 17134
系统型号:         TUF Gaming FX505GE_FX86FE
系统类型:         x64-based PC

**Comment by Medicean** [comment]
这是正常功能
