### ISSUE TITLE
Linux运行报错

### ISSUE THREAD

**Issue by Moon3r** [AntSwordProject/AntSword-Loader#2]
Ubuntu16.04环境下开始无法自动解压，解决完解压问题后继续打开应用，会有弹框提示错误，并且重新打开会卡在启动界面

**Comment by Medicean** [comment]
能否贴一下截图

**Comment by Moon3r** [comment]
之前的报错无法复现了，如果再次出现的话把图贴上来，安装完成后打开卡在启动界面的问题能否先解决一下呢？

**Comment by Medicean** [comment]
该问题是由新功能导致，已经解决。https://github.com/AntSwordProject/antSword/commit/cbb67dd0d86770f8299cd327c8ccf7adadbf68c9
