### ISSUE TITLE
加载器选择路径后显示Not Found

### ISSUE THREAD

**Issue by ghost** [AntSwordProject/AntSword-Loader#20]
选择目录后加载器显示“监测到未安装代码，准备安装中“
然后就出现空白页面，显示”Not Found“
我用的是OSX 10.15.2
请问怎么解决啊

**Comment by sqlsec** [comment]
是因为官方主项目被删了 如果要安装的话 可以拷贝其他师傅的antsword里面的内容 安装的时候会检测到代码就会直接跳过初始化了。

**Comment by ghost** [comment]
> 是因为官方主项目被删了 如果要安装的话 可以拷贝其他师傅的antsword里面的内容 安装的时候会检测到代码就会直接跳过初始化了。

原来如此，感谢

**Comment by HackerYunen** [comment]
> 是因为官方主项目被删了 如果要安装的话 可以拷贝其他师傅的antsword里面的内容 安装的时候会检测到代码就会直接跳过初始化了。

目前只能找到19年11月版的（gitee的mirror），师傅有官方仓库最新的版本嘛。求 : )
