### ISSUE TITLE
MAC加载器安装后，缺少部分功能入口

### ISSUE THREAD

**Issue by FlyingPikachus** [AntSwordProject/AntSword-Loader#25]
![image](https://user-images.githubusercontent.com/39126781/98710992-5fec9d00-23bf-11eb-9741-6fdf6428a0c2.png)

**Comment by Medicean** [comment]
缺啥功能？

**Comment by FlyingPikachus** [comment]
换个说法，如何在mac版蚁剑应用窗口使用插件等其他win上类似的功能。

**Comment by Medicean** [comment]
你是不是在说菜单? 左上角。
