### ISSUE TITLE
蚁剑的上传文件超时时间在哪里调整？

### ISSUE THREAD

**Issue by Khushashi** [AntSwordProject/AntSword-Loader#28]
上传文件发现提示上传失败，请将超时时间调整到最大
但是到设置里面看了一下没有设置超时时间的这个选项，有没有人能讲一下怎么设置超时时间

**Comment by Khushashi** [comment]
@Medicean

**Comment by Medicean** [comment]
参见：
https://doc.u0u.us/zh-hans/shell_manager/shell_config.html

请求超时
