### ISSUE TITLE
Kali Linux Xfce 64 Bit平台下打开文件管理页面文字、标题乱码

### ISSUE THREAD

**Issue by GitHubNull** [AntSwordProject/AntSword-Loader#4]
Kali Linux Xfce 64 Bit平台下中文界面，不论是什么情况下打开文件管理器都会出现标题文字、文件名、属性等等乱码。

**Comment by Medicean** [comment]
这个是已知问题，在 #3  2楼回复中已经说过了。

> electron 1.2.3 版本在 kali 下面文件选择框字符无法正常显示，后续整体升级 electron 后会解决乱码这一问题。

近期可能会针对 kali 发一个测试版的加载器

**Comment by GitHubNull** [comment]
收到，辛苦了!

**Comment by 0x2E** [comment]
Ubuntu18.04 出现相同问题，期待大佬更新。

**Comment by Medicean** [comment]
注意：该加载器只能加载 v2.1.x 分支代码, 请务必使用下面

1. 第一步 clone AntSword 源代码
```
$ git clone https://github.com/AntSwordProject/antSword.git -b v2.1.x
```

2. 下载Linux测试版本加载器(v2.1.0)

链接: [AntSword-Loader-v2.1.0-linux-x64.zip](http://as.xuanbo.cc/AntSword-Loader-v2.1.0-linux-x64.zip)

3. 打开加载器，选择第1步 clone 好的代码

**Comment by Medicean** [comment]
已发布新版本加载器，可解决该问题 https://github.com/AntSwordProject/AntSword-Loader/tree/4.0.3
