### ISSUE TITLE
加载器不检测已解压的文件只检测压缩包

### ISSUE THREAD

**Issue by Gh6636963153** [AntSwordProject/AntSword-Loader#40]
![image](https://user-images.githubusercontent.com/90520095/207504192-d45ccfcb-8c54-497a-bb43-c9c09dd9402c.png)
我的已经安装到这里了，也解压出来了但加载器一直报代码解压出错是什么鬼。
  而且目录不是选择app.js所在的目录，而是它的上级目录，它会自动下载antSword-master,然后自己解压运行。
  如果你解压好了它是不检测的，它只检测压缩包，有压缩包它就自己给你解压，如果解不了它就运行不了，就像我这个一样我解压出来了它就不运行

**Comment by Medicean** [comment]
不要抬杠哈，这是加载器，不是 AI 。文档里面怎么写的，怎么操作就行了

**Comment by Gh6636963153** [comment]
首先我表明下自己态度，我并没有去抬杠，只是我按照手册去做确实遇到了这个问题，我客观的阐述下自己遇到的问题。
操作过程我录制视频了，在附件里。
还有我的观点是能在github上分享源码的技术人员都是值得尊敬的人，同时我自己也是做网络技术的，也是喜欢分享技术的人。
至于我的发言为什么让你感到是抬杠，可能是我的用词不当造成的，
在平时聊技术的时候，不好的措词用习惯了，在此我真诚的表达自己的歉意。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "AntSwordProject/AntSword-Loader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月21日(星期三) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntSwordProject/AntSword-Loader] 加载器不检测已解压的文件只检测压缩包 (Issue #40)





 
不要抬杠哈，这是加载器，不是 AI 。文档里面怎么写的，怎么操作就行了

**Comment by Medicean** [comment]
为我之前的回复表示抱歉。

加载器是 4 年前的东西，里面功能写的比较简单，没有处理那么多异常问题。还请理解。

这块后面会慢慢再优化的。

**Comment by Gh6636963153** [comment]
OK，我提问题的本意就是，把软件的问题暴露出来，让它更加完善。
因为我觉得它是挺不错的软件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntSwordProject/AntSword-Loader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月22日(星期四) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntSwordProject/AntSword-Loader] 加载器不检测已解压的文件只检测压缩包 (Issue #40)





 
为我之前的回复表示抱歉。
 
加载器是 4 年前的东西，里面功能写的比较简单，没有处理那么多异常问题。还请理解。
 
这块后面会慢慢再优化的。
