### ISSUE TITLE
osx 平台下,复制粘贴问题,和一些功能建议

### ISSUE THREAD

**Issue by pinklinux** [AntSwordProject/AntSword-Loader#5]
1:操作了一段时间后,复制粘贴有问题,用鼠标选择,然后 ctrl+c .ctrl+v粘贴内容,居然是鼠标选择的内容.如果重启客户端之后,又会恢复,操作一会之后就又不行了.

2:还有导出 shell 配置,导入的时候,报错退出!.

3:建议数据库管理,可以选择保存执行过的命令,方便下次使用.最好能加上多句执行呀,复制所有需要执行的命令,一次执行,跟 phpmyadmin 一样.😝

4:数据库执行之后返回的内容,希望能导出或者复制,能右键显示之前执行过的所有命令.

**Comment by Medicean** [comment]
> 功能上的问题请移步到 antSword 项目下面提 issue, 这里只处理关于 loader 的问题,望理解

1. osx 下的复制粘贴是 Command+c 和 Command+v 不是 ctrl +c

2. 你可以手动改改 _id 里面的东西之后再试 (这个问题应该提在 importshell 项目下)

3. 多语句这个得看目标配置是否支持多语句(这边可以用多次发包来做)

4. 计划中，可能会在 v2.1 中会推出
