### ISSUE TITLE
方便来个32位的吗

### ISSUE THREAD

**Issue by 0ps** [AntSwordProject/AntSword-Loader#6]
方便来个32位的吗

**Comment by Medicean** [comment]
提供一下操作系统？另外我这边没有32位的操作系统，可以帮我测试吗

**Comment by 0ps** [comment]
vm就行啊。可以帮你测试

**Comment by U2FsdGVkX1** [comment]
@Medicean 
32位可以有么，Electron应该很好编译吧

**Comment by Medicean** [comment]
已经编译好了 linux ia32 、arm64、armv7l 。不过没怎么测试，可以试一下。

**Comment by U2FsdGVkX1** [comment]
@Medicean 
希望还可以有个 Windows x86 版的，需要测试我可以帮你

**Comment by Medicean** [comment]
windows 的等明天吧

**Comment by Medicean** [comment]
AntSword-Loader-v4.0.3-win32-ia32.zip 已经发布，可以测试一下

**Comment by U2FsdGVkX1** [comment]
@Medicean 
启动器初始化的自动下载会提示「代码解压出错：[object Object]」，下载下来的压缩文件是正常的，在手动解压了之后正常启动，现在使用功能基本都是正常的

感谢！

**Comment by Medicean** [comment]
如果你有一定的 git 基础的话，建议你直接用 git 来管理源代码。尽量不要用加载器中自带的 http 来管理。

**Comment by U2FsdGVkX1** [comment]
对的，现在在用 git 管理源代码，使用没什么问题

**Comment by U2FsdGVkX1** [comment]
已解决，是我本机设置问题
